parameters:
    blend_partial_content.blogcontroller.class: Blend\PartialContentBundle\Controller\BlogController

services:
    blend_partial_content.controller:
        class: %blend_partial_content.blogcontroller.class%
        arguments: [@ezpublish.view_manager]
        calls:
            - [ setContainer, [@service_container] ]

    pcblog:
        alias: blend_partial_content.controller
