parameters:
#    blend_partial_content.example.class: Blend\PartialContentBundle\Example

services:
#    blend_partial_content.example:
#        class: %blend_partial_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
